feat: adds open-runtimes for node-19 latest release
open-runtimes/open-runtimes pull request #105
Opened 2022-10-21 15:43 UTC by afzal442

Signed-off-by: afzal442 <afzal442@gmail.com>

2022-10-21 17:28 UTC, afzal442 commented
hey @stnguyen90 ! Can you review this PR? Thanks 😄

2022-10-24 06:14 UTC, afzal442 commented
Any review plz?

cc @stnguyen90

2022-10-25 14:25 UTC, afzal442 commented
Any thought here?

cc @stnguyen90

2022-10-26 21:37 UTC, stnguyen90 commented
I don't think we want to add this at the moment because we'd rather only support the LTS versions.

2022-10-28 17:55 UTC, afzal442 commented
hey @stnguyen90 can you approve if this okay as part of Hacktoberfest? 🎐

2022-10-28 18:34 UTC, stnguyen90 commented
> hey @stnguyen90 can you approve it if this okay as part of Hacktoberfest? 🎐

https://github.com/open-runtimes/open-runtimes/pull/105#issuecomment-1292680913

2022-10-31 16:28 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-15 21:13 UTC, stnguyen90 commented
Closing as we want to focus on LTS releases

2022-11-17 00:54 UTC, stnguyen90 commented
Re-opening because we're reconsidering whether to support node 19 or not 😅

2022-11-17 19:40 UTC, stnguyen90 commented
@afzal442, btw, if we do decide to add support for node 19, this PR will need tests to ensure the CI passes.

2022-11-18 17:10 UTC, afzal442 commented
Thank you @stnguyen90 for reconsidering it. 😄 Looking forward to adding CI tests for this soon.

2023-01-09 22:28 UTC, stnguyen90 requested changes
Have you had a chance to fix the CI?

2023-01-10 13:45 UTC, afzal442 commented
Hey @stnguyen90, I just did that. Thanks for that to push me up. 😃

2023-01-11 00:47 UTC, stnguyen90 approved these changes
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2023-04-06 21:54 UTC, christyjacob4 commented on runtimes/node-19.0/README.md
> +
```suggestion
```

2023-04-06 21:55 UTC, christyjacob4 approved these changes

2023-04-06 21:55 UTC, merged

2023-04-06 21:55 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)