Docs: Usage script readability
open-runtimes/open-runtimes pull request #135
Opened 2023-01-24 10:17 UTC by Meldiron

This PR makes usage example scripts:

- More readable for humans
- Copyable from readme
- Copyable from terminal

2023-01-24 17:58 UTC, Meldiron commented
Tested all scripts manually

2023-01-24 20:33 UTC, gewenyu99 requested changes
I'm good with this, 1 comment. Only concern is that you clearly explain what `tee` does in the instructions preceding this code block.

2023-01-24 20:33 UTC, gewenyu99 commented on runtimes/dotnet-3.1/README.md
> +    return res.Json(new Dictionary<string, object>() {{ "n", new System.Random().NextDouble() }} );
We can probably format this better, now that we use `tee`

2023-01-25 06:53 UTC, Meldiron commented
@gewenyu99 above script we say `Add code into "Index.cs" file`. Do you think that is good enough or we should be more specific?

2023-01-31 17:37 UTC, gewenyu99 commented
> @gewenyu99 above script we say `Add code into "Index.cs" file`. Do you think that is good enough or we should be more specific?

Good enough for now :)

2023-01-31 17:38 UTC, gewenyu99 approved these changes
LGTM

2023-02-07 11:19 UTC, Meldiron commented
This will be broken by V3. New branch should be started when v3 is merged.

2023-03-01 12:13 UTC, Meldiron commented
Closing in favour of: https://github.com/open-runtimes/open-runtimes/pull/154

2023-03-01 12:13 UTC, closed without merging