Feat: ES module support (Node)
open-runtimes/open-runtimes pull request #67
Opened 2022-03-25 08:10 UTC by Meldiron

Issue: https://github.com/open-runtimes/open-runtimes/issues/63

If you have `index.ts`:
![CleanShot 2022-03-25 at 09 08 27](https://user-images.githubusercontent.com/19310830/160080634-4d9f9a5c-8295-444a-82d1-1913c5e25919.png)

It will build to `index.js`:

![CleanShot 2022-03-25 at 09 08 30](https://user-images.githubusercontent.com/19310830/160080656-b1a7c75f-16b1-4ce6-99f4-6fb861cb8205.png)

OPR for Node now supports this, and executes properly:

![CleanShot 2022-03-25 at 09 08 22](https://user-images.githubusercontent.com/19310830/160080701-698cdbca-f960-4d7f-94c7-d059e061b903.png)

2022-03-25 11:10 UTC, christyjacob4 approved these changes

2022-03-25 12:59 UTC, JakeAi commented
If you keep the sanity check, you may want to check if `userFunction.default` is also a function, and I would maybe look into changing the error message to something along the lines of "The exported code must export a function."

2022-03-28 06:50 UTC, christyjacob4 commented
@JakeAi  I think that's a good suggestion. 
@Meldiron Please incorporate this check as well.

2022-03-28 06:50 UTC, christyjacob4 requested changes
@JakeAi  I think that's a good suggestion. 
@Meldiron Please incorporate this check as well.

2022-04-01 13:14 UTC, christyjacob4 approved these changes

2022-04-01 13:14 UTC, merged