ruby: print actual execption on user code failure
open-runtimes/open-runtimes pull request #70
Opened 2022-03-31 10:00 UTC by lohanidamodar

2022-03-31 10:52 UTC, Meldiron approved these changes
If tests don't cover the topic, it would be great to always include QA screenshots in the description.

Other than that, LGTM.

2022-03-31 23:05 UTC, abnegate approved these changes

2022-04-01 12:28 UTC, christyjacob4 commented on runtimes/ruby-3.0/server.rb
> +    return { code: 500, message: "Exception Occurred #{e.class}. Message: #{e.message}. Backtrace:  \n #{e.backtrace.join("\n")}" }.to_json
```suggestion
    return { code: 500, message: "#{e.backtrace.join("\n")}" }.to_json
```

2022-04-01 12:28 UTC, christyjacob4 commented on runtimes/ruby-3.1/server.rb
> +    return { code: 500, message: "Exception Occurred #{e.class}. Message: #{e.message}. Backtrace:  \n #{e.backtrace.join("\n")}" }.to_json
```suggestion
    return { code: 500, message: "#{e.backtrace.join("\n")}" }.to_json
```
Just the trace is good enough 👍

2022-04-01 12:28 UTC, christyjacob4 requested changes
minor comment

2022-04-03 14:21 UTC, merged